export const CATEGORY_ACTION_TYPES = {
    SET_CATEGORIES_START: "category/SET_CATEGORIES_START",
    SET_CATEGORIES_SUCCESS: "category/SET_CATEGORIES_SUCCESS",
    SET_CATEGORIES_FAILED: "category/SET_CATEGORIES_FAILED",
};
